config/routes.rb
Rails.application.routes.draw do
  root 'cocktails#index'
  get 'cocktails', to: 'cocktails#index'
  get 'cocktails/new', to: 'cocktails#new'
  post 'cocktails', to: 'cocktails#create'
  get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'
  get 'cocktails/:id/ingredients', to: 'cocktails#ingredients'
  get 'cocktails/:cocktail_id/doses/new', to: 'doses#new', as: 'doses'
  post 'cocktails/:cocktail_id/doses', to: 'doses#create'
  delete 'doses/:id', to: 'doses#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, :presence => true
  validates_uniqueness_of :name
  has_many :doses, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, :presence => true
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, :presence => true
  validates_uniqueness_of :name
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def ingredients
    @cocktail = Cocktail.find(params[:id])
    @ingredients = @cocktail.ingredients
  end

  private def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(cocktail_id: @cocktail.id)
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.create(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to doses_path
  end

  private

  def dose_params
    params.require(:dose).permit(:amount, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <p>
    <%= link_to "Create New Cocktail", cocktails_new_path %>
  </p>
  <h1>Available Cocktails</h1>
  <%= cl_image_tag("cocktails_thinkstockphotos-530433362",
      width: 400, height: 300, crop: :fill) %>

  <div class="cocktails">
    <% @cocktails.each do |cocktail| %>
      <div class="cocktail--preview">
        <p><%= cocktail.name %></p>
        <%= link_to "More details", cocktail_path(cocktail) %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <%= link_to "Back to all cocktails", cocktails_path %>

  <h1>New cocktail</h1>

  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <%= link_to "Back to all cocktails", cocktails_path %>
  <h1><%= @cocktail.name %></h1>
  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

  <div>
    <h2>Doses</h2>
    <% @cocktail.doses.each do |dose| %>
      <div class="cocktail_dose">
        <p>Ingredient: <%= dose.ingredient.name %></p>
        <p>Amount: <%= dose.amount %></p>
        <p>Description: <%= dose.description %></p>
      </div>
    <% end %>

    <h2>Ingredients</h2>
    <% @cocktail.ingredients.each do |ingredient| %>
      <div>
        <p>Name: <%= ingredient.name %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <%= link_to "Back to all cocktails", cocktails_path %>

  <h1>New dose</h1>

  <%= form_for(@dose) do |f| %>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
<%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
<%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</html>